### PR TITLE
enable www.xiaomi.com full site

### PR DESCRIPTION
**Pull request by raydemandforce**
The old configuration does not work for xiaomi anymore, I am updating the configuration.

### CODE REVIEW

**Comment by zhuzhuor** [comment]
I guess you meant xiami, not xiaomi?

**Comment by zhuzhuor** [comment]
Could you also try if xiami's VIP works for people travelling outside China?
http://www.xiami.com/vip

Previous discussions can be found at https://github.com/Unblocker/Unblock-Youku/issues/381

**Comment by raydemandforce** [comment]
vip 可以用。 那我先关了这个pr

**Comment by zhuzhuor** [comment]
@raydemandforce Thanks for the info!

**Pull request closed without merging**
